#!/bin/bash

__vg_reload() {
    PROMPT_COMMAND=$_VIRTUALGO_ORIGINAL_PROMPT_COMMAND
    eval "$(vg eval --shell bash)"
}

_PREV_VIRTUALGO_PWD=""

__vg_prompt_command() {
    if [ "$PWD" = "$_PREV_VIRTUALGO_PWD" ]; then
        return
    fi
    _PREV_VIRTUALGO_PWD="$PWD"

    __vg_auto_activate
}

_VIRTUALGO_ORIGINAL_PROMPT_COMMAND=$PROMPT_COMMAND
PROMPT_COMMAND="__vg_prompt_command ; $PROMPT_COMMAND"
